services:
  web:
    image: nginx:stable-alpine
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - './docker/web/nginx.conf:/etc/nginx/conf.d/default.conf'
        - './public:/var/www/public'
    networks:
      - app-network
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: php-fpm
    user: '${UID:-1000}:${GID:-1000}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/var/www/html'
      - '.:/docker/app/xdebug.ini:/etc/php/8.3/cli/conf.d/20-xdebug.ini'
    working_dir: '/var/www/html'
    depends_on:
      - mysql
      - redis
    environment:
      PHP_IDE_CONFIG: "serverName=DevServer"
    networks:
        - app-network
  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'
  mysql_test:
    image: 'mysql/mysql-server:8.0'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_ROOT_HOST: '%'
    ports:
        - '3307:3306'
    volumes:
        - 'mysql_test:/var/lib/mysql'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysql:
  mysql_test:
  redis:
