<?php

namespace Tests\Feature\Controller\User;

use App\Models\User;
use Closure;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Testing\TestResponse;
use PHPUnit\Framework\Attributes\DataProvider;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;
use Tests\Traits\UserTrait;

class UserUpdateTest extends TestCase
{
    private const CONTROLLER_ROUTE = '/api/user/';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        UserTrait::createAdminAuthorizedUser();
    }

    public function testUpdateUserSuccess(): void
    {
        $updateUserData = [
            'name' => 'testName',
            'email' => 'shvartznigger@gmail.com',
            'default_address' => 'г. Магнитогорск',
        ];

        $user = auth()->user();

        $response = $this->patchJson(
            self::CONTROLLER_ROUTE . $user->getAuthIdentifier(),
            $updateUserData,
            ['authorization' => 'Bearer ' . auth()->getToken()]
        );

        $response->assertOk();
        $response->assertJson([
            'name' => $updateUserData['name'],
            'surname' => $user->surname,
            'email' => $updateUserData['email'],
            'phone' => $user->phone,
            'default_address' => $updateUserData['default_address'],
        ]);
    }

    #[DataProvider('userUpdateFailureProvider')]
    public function testUpdateUserFailure(
        array    $updateUserData,
        ?Closure $anotherUserId,
        ?string  $invalidToken,
        Closure  $assertions,
    ): void {
        $userId = $anotherUserId ? $anotherUserId() : auth()->user()->getKey();
        $accessToken = $invalidToken ?? auth()->getToken();

        $response = $this->patchJson(
            self::CONTROLLER_ROUTE . $userId,
            $updateUserData,
            ['authorization' => 'Bearer ' . $accessToken]
        );

        $assertions($response);
    }

    public static function userUpdateFailureProvider(): array
    {
        return [
            'updateWithInvalidDataShouldFail' => [
                'updateUserData' => [
                    'phone' => 'invalid phone number',
                    'name' => 'shvartznigger@gmail.com',
                ],
                'anotherUserId' => null,
                'invalidToken' => null,
                'assertions' => function (TestResponse $response) {
                    $response->assertStatus(Response::HTTP_BAD_REQUEST);
                    $decodedResponse = $response->decodeResponseJson();

                    static::assertArrayHasKey('message', $decodedResponse);
                    static::assertSame('The given data failed to pass validation', $decodedResponse['message']);
                },
            ],
            'updateNonExistentUserShouldFail' => [
                'updateUserData' => [
                    'name' => 'testName',
                    'email' => 'shvartznigger@gmail.com',
                    'default_address' => 'г. Магнитогорск',
                ],
                'anotherUserId' => fn() => 10000,
                'invalidToken' => null,
                'assertions' => function (TestResponse $response) {
                    $response->assertStatus(Response::HTTP_NOT_FOUND);
                    $decodedResponse = $response->decodeResponseJson();

                    static::assertArrayHasKey('message', $decodedResponse);
                    static::assertSame('Resource is not exist', $decodedResponse['message']);
                },
            ],
            'updateAnotherUserShouldFail' => [
                'updateUserData' => [
                    'name' => 'testName',
                    'email' => 'shvartznigger@gmail.com',
                    'default_address' => 'г. Магнитогорск',
                ],
                'anotherUserId' => fn() => UserTrait::getAnotherUser()->getKey(),
                'invalidToken' => null,
                'assertions' => function (TestResponse $response) {
                    $response->assertStatus(Response::HTTP_UNAUTHORIZED);
                    $decodedResponse = $response->decodeResponseJson();

                    static::assertArrayHasKey('message', $decodedResponse);
                    static::assertSame('Don\'t have permission to this resource', $decodedResponse['message']);
                },
            ],
            'updateRequestWithInvalidTokenShouldFail' => [
                'updateUserData' => [
                    'name' => 'testName',
                    'email' => 'shvartznigger@gmail.com',
                    'default_address' => 'г. Магнитогорск',
                ],
                'anotherUserId' => null,
                'invalidToken' => 'eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEifQ.ZAU547bnCcGrvSZiaDeYpbQg6rUopOe3HMJ01l2a2NQ',
                'assertions' => function (TestResponse $response) {
                    $response->assertStatus(Response::HTTP_UNAUTHORIZED);
                    $decodedResponse = $response->decodeResponseJson();

                    static::assertArrayHasKey('message', $decodedResponse);
                    static::assertSame('Token Signature could not be verified.', $decodedResponse['message']);
                },
            ],
        ];
    }
}
