<?php

namespace Tests\Feature\Controller\User;

use PHPUnit\Framework\Attributes\DataProvider;
use Tests\TestCase;

class UserUpdateTest extends TestCase
{
    private const USER_CONTROLLER_ROUTE = '/api/users/{userId}';
    private const ADMIN_CONTROLLER_ROUTE = '/api/admin/users/{userId}';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    #[DataProvider('contextDataProvider')]
    public function testUpdateUserShouldSuccess(\Closure $user, string $route): void
    {
        $user = $user($this);
        $updateUserData = [
            'name' => 'testName',
            'surname' => 'testSurname',
            'email' => 'shvartznigger@gmail.com',
            'phone' => '89963254558',
            'defaultAddress' => 'г. Магнитогорск',
        ];

        $response = $this->putJson(
            str_replace('{userId}', $user->getKey(), $route),
            $updateUserData,
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );
        $expectedResult = $updateUserData;
        $expectedResult['default_address'] = $expectedResult['defaultAddress'];
        unset($expectedResult['defaultAddress']);

        $response->assertOk();
        $response->assertJson($expectedResult);
    }

    public function testAnotherUserShouldSuccess(): void
    {
        $user = $this->getAdminUser();
        $anotherUser = $this->getAnotherUser();
        $updateUserData = [
            'name' => 'testName',
            'surname' => 'testSurname',
            'email' => 'shvartznigger@gmail.com',
            'phone' => '89963254558',
            'defaultAddress' => 'г. Магнитогорск',
        ];

        $response = $this->putJson(
            str_replace('{userId}', $anotherUser->id, self::ADMIN_CONTROLLER_ROUTE),
            $updateUserData,
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $expectedResult = $updateUserData;
        $expectedResult['default_address'] = $expectedResult['defaultAddress'];
        unset($expectedResult['defaultAddress']);

        $response->assertOk();
        $response->assertJson($expectedResult);
    }

    public function testAnotherUserShouldFail()
    {
        $user = $this->getUser();
        $anotherUser = $this->getAnotherUser();
        $updateUserData = [
            'name' => 'testName',
            'surname' => 'testSurname',
            'email' => 'shvartznigger@gmail.com',
            'phone' => '89963254558',
            'defaultAddress' => 'г. Магнитогорск',
        ];

        $response = $this->putJson(
            str_replace('{userId}', $anotherUser->id, self::USER_CONTROLLER_ROUTE),
            $updateUserData,
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertForbidden();
    }

    #[DataProvider('contextDataProvider')]
    public function testUpdateUserWithInvalidDataShouldFail(\Closure $user, string $route)
    {
        $user = $user($this);
        $updateUserData = [
            'name' => 'testName',
            'surname' => 'testSurname',
            'email' => 'shvartznigger@gmail.com',
            'phone' => 'invalid phone number',
            'defaultAddress' => 'г. Магнитогорск',
        ];

        $response = $this->putJson(
            str_replace('{userId}', $user->getKey(), $route),
            $updateUserData,
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertUnprocessable();
    }

    #[DataProvider('contextDataProvider')]
    public function testUpdateNonExistentUserShouldFail(\Closure $user, string $route)
    {
        $user = $user($this);
        $updateUserData = [
            'name' => 'testName',
            'surname' => 'testSurname',
            'email' => 'shvartznigger@gmail.com',
            'phone' => '89963254558',
            'defaultAddress' => 'г. Магнитогорск',
        ];

        $response = $this->putJson(
            str_replace('{userId}', rand(1000, 2000), $route),
            $updateUserData,
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertNotFound();
    }


    #[DataProvider('contextDataProvider')]
    public function testUpdateUserWithInvalidTokenShouldFail(\Closure $user, string $route)
    {
        $user = $user($this);
        $updateUserData = [
            'name' => 'testName',
            'surname' => 'testSurname',
            'email' => 'shvartznigger@gmail.com',
            'phone' => '89963254558',
            'defaultAddress' => 'г. Магнитогорск',
        ];

        $response = $this->putJson(
            str_replace('{userId}', $user->id, $route),
            $updateUserData,
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }

    public static function contextDataProvider(): array
    {
        return [
            'user' => [
                'user' => fn ($self) => $self->getUser(),
                'route' => self::USER_CONTROLLER_ROUTE,
            ],
            'admin' => [
                'user' => fn ($self) => $self->getAdminUser(),
                'route' => self::ADMIN_CONTROLLER_ROUTE,
            ]
        ];
    }
}
