<?php

namespace Tests\Feature\Controller\User;

use PHPUnit\Framework\Attributes\DataProvider;
use Tests\TestCase;

class UserGetTest extends TestCase
{
    private const USER_CONTROLLER_ROUTE = '/api/users/{userId}';
    private const ADMIN_CONTROLLER_ROUTE = '/api/admin/users/{userId}';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    #[DataProvider('contextDataProvider')]
    public function testGetUserShouldSuccess(\Closure $user, string $route): void
    {
        $user = $user($this);

        $response = $this->getJson(
            str_replace('{userId}', $user->getKey(), $route),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertOk();
        $response->assertJson([
            'name' => $user->name,
            'surname' => $user->surname,
            'email' => $user->email,
            'phone' => $user->phone,
            'default_address' => $user->default_address,
        ]);
    }

    public function testGetAnotherUserShouldSuccess()
    {
        $user = $this->getAdminUser();
        $anotherUser = $this->getAnotherUser();

        $response = $this->getJson(
            str_replace('{userId}', $anotherUser->id, self::USER_CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertOk();
        $response->assertJson([
            'name' => $anotherUser->name,
            'surname' => $anotherUser->surname,
            'email' => $anotherUser->email,
            'phone' => $anotherUser->phone,
            'default_address' => $anotherUser->default_address,
        ]);
    }

    #[DataProvider('contextDataProvider')]
    public function testGetNonExistentUserShouldFail(\Closure $user, string $route)
    {
        $user = $user($this);

        $response = $this->getJson(
            str_replace('{userId}', rand(1000, 2000), $route),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertNotFound();
    }

    public function testGetAnotherUserShouldFail()
    {
        $user = $this->getUser();
        $anotherUser = $this->getAnotherUser();

        $response = $this->getJson(
            str_replace('{userId}', $anotherUser->id, self::USER_CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertForbidden();
    }

    #[DataProvider('contextDataProvider')]
    public function testUserWithInvalidTokenShouldFail(\Closure $user, string $route)
    {
        $user = $user($this);

        $response = $this->getJson(
            str_replace('{userId}', $user->id, $route),
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }

    public static function contextDataProvider(): array
    {
        return [
            'user' => [
                'user' => fn ($self) => $self->getUser(),
                'route' => self::USER_CONTROLLER_ROUTE,
            ],
            'admin' => [
                'user' => fn ($self) => $self->getAdminUser(),
                'route' => self::ADMIN_CONTROLLER_ROUTE,
            ]
        ];
    }
}
