<?php

namespace Tests\Feature\Controller\User;

use Closure;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Testing\TestResponse;
use PHPUnit\Framework\Attributes\DataProvider;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;
use Tests\Traits\UserTrait;

class UserDeleteTest extends TestCase
{
    private const USER_CONTROLLER_ROUTE = '/api/users/{userId}';
    private const ADMIN_CONTROLLER_ROUTE = '/api/admin/users/{userId}';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    #[DataProvider('contextDataProvider')]
    public function testDeleteUserShouldSuccess(\Closure $user, string $route): void
    {
        $user = $user($this);

        $response = $this->deleteJson(
            str_replace('{userId}', $user->id, $route),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );
        $response->assertOk();
        static::assertModelMissing($user);
    }

    public function testDeleteAnotherUserShouldSuccess(): void
    {
        $user = $this->getAdminUser();
        $anotherUser = $this->getAnotherUser();

        $response = $this->deleteJson(
            str_replace('{userId}', $anotherUser->id, self::ADMIN_CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertOk();
        static::assertModelMissing($anotherUser);
    }

    public function testDeleteAnotherUserShouldFail(): void
    {
        $user = $this->getUser();
        $anotherUser = $this->getAnotherUser();

        $response = $this->deleteJson(
            str_replace('{userId}', $anotherUser->id, self::USER_CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertForbidden();
    }

    #[DataProvider('contextDataProvider')]
    public function testDeleteNonExistentUserShouldFail(\Closure $user, string $route): void
    {
        $user = $user($this);

        $response = $this->deleteJson(
            str_replace('{userId}', rand(1000, 2000), $route),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertNotFound();
    }

    #[DataProvider('contextDataProvider')]
    public function testDeleteUserWithInvalidTokenShouldFail(\Closure $user, string $route): void
    {
        $user = $user($this);
        $response = $this->deleteJson(
            str_replace('{userId}', $user->id, $route),
            [],
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }

    public static function contextDataProvider(): array
    {
        return [
            'user' => [
                'user' => fn ($self) => $self->getUser(),
                'route' => self::USER_CONTROLLER_ROUTE,
            ],
            'admin' => [
                'user' => fn ($self) => $self->getAdminUser(),
                'route' => self::ADMIN_CONTROLLER_ROUTE,
            ]
        ];
    }
}
