<?php

namespace Tests\Feature\Controller\Cart;

use PHPUnit\Framework\Attributes\DataProvider;
use Tests\TestCase;

class CartDeleteTest extends TestCase
{
    private const USER_CONTROLLER_ROUTE = '/api/users/{userId}/carts';
    private const ADMIN_CONTROLLER_ROUTE = '/api/admin/users/{userId}/carts';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testDeleteCartByOwnerSuccess(): void
    {
        $user = $this->createUser();
        $this->createCartProducts($user);

        $response = $this->deleteJson(
            str_replace('{userId}', $user->getKey(), self::USER_CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertOk();
        static::assertTrue($user->products()->get()->isEmpty());
    }

    public function testDeleteCartByAdminSuccess(): void
    {
        $user = $this->getAdminUser();
        $anotherUser = $this->createUser();
        $this->createCartProducts($anotherUser);

        $response = $this->deleteJson(
            str_replace('{userId}', $user->getKey(), self::ADMIN_CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertOk();
        static::assertTrue($user->products()->get()->isEmpty());
    }

    #[DataProvider('contextDataProvider')]
    public function testDeleteCartWithInvalidTokenShouldFail(\Closure $user, string $route): void
    {
        $user = $user($this);
        $this->createCartProducts($user);

        $response = $this->deleteJson(
            str_replace('{userId}', $user->getKey(), $route),
            [],
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }

    #[DataProvider('contextDataProvider')]
    public function testDeleteAnotherUserCartShouldFail(\Closure $user, string $route): void
    {
        $user = $user($this);
        $anotherUser = $this->createUser();
        $this->createCartProducts($anotherUser);

        $response = $this->deleteJson(
            str_replace('{userId}', $anotherUser->getKey(), $route),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertForbidden();
    }

    public static function contextDataProvider(): array
    {
        return [
            'user' => [
                'user' => fn ($self) => $self->getUser(),
                'route' => self::USER_CONTROLLER_ROUTE,
            ],
            'admin' => [
                'user' => fn ($self) => $self->getAdminUser(),
                'route' => self::ADMIN_CONTROLLER_ROUTE,
            ]
        ];
    }
}
