<?php

namespace Tests\Feature\Controller\Cart;

use App\Exceptions\Resource\ResourceAccessException;
use Illuminate\Support\Facades\Exceptions;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;

class CartDeleteTest extends TestCase
{
    private const CONTROLLER_ROUTE = '/api/users/{userId}/carts';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testDeleteCartByOwnerSuccess(): void
    {
        $user = $this->createUser();
        $this->createCartProducts($user);

        $response = $this->deleteJson(
            str_replace('{userId}', $user->getKey(), self::CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertOk();
        static::assertTrue($user->products()->get()->isEmpty());
    }

    public function testDeleteCartByAdminSuccess(): void
    {
        $user = $this->getAdminUser();
        $anotherUser = $this->createUser();
        $this->createCartProducts($anotherUser);

        $response = $this->deleteJson(
            str_replace('{userId}', $user->getKey(), self::CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertOk();
        static::assertTrue($user->products()->get()->isEmpty());
    }

    public function testDeleteCartWithInvalidTokenShouldFail(): void
    {
        $user = $this->createUser();
        $this->createCartProducts($user);

        $response = $this->deleteJson(
            str_replace('{userId}', $user->getKey(), self::CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . self::$this->getInvalidToken()]
        );

        $response->assertStatus(Response::HTTP_UNAUTHORIZED);
        $decodedResponse = $response->decodeResponseJson();

        static::assertArrayHasKey('message', $decodedResponse);
        static::assertSame('Token Signature could not be verified.', $decodedResponse['message']);
    }

    public function testDeleteAnotherUserCartShouldFail(): void
    {
        $user = $this->createUser();
        $anotherUser = $this->createUser();
        $this->createCartProducts($anotherUser);

        Exceptions::fake();
        $response = $this->deleteJson(
            str_replace('{userId}', $anotherUser->getKey(), self::CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertStatus(Response::HTTP_UNAUTHORIZED);
        Exceptions::assertReported(ResourceAccessException::class);
    }
}
