<?php

namespace Tests\Feature\Controller\Cart;

use Tests\TestCase;

class CartGetTest extends TestCase
{
    private const CONTROLLER_ROUTE = '/api/users/{userId}/carts';
    private const ADMIN_CONTROLLER_ROUTE = '/api/admin/users/{userId}/carts';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetCartByOwnerSuccess(): void
    {
        $user = $this->getUser();
        $expectedCart = $this->getCart($user);
        $response = $this->getJson(
            str_replace('{userId}', $user->getKey(), self::CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertOk();
        $response->assertJson($expectedCart);
    }

    public function testGetCartByAdminSuccess(): void
    {
        $adminUser = $this->getAdminUser();
        $anotherUser = $this->getAnotherUser();
        $expectedCart = $this->getCart($anotherUser);

        $response = $this->getJson(
            str_replace('{userId}', $anotherUser->getKey(), self::ADMIN_CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($adminUser)]
        );

        $response->assertOk();
        $response->assertJson($expectedCart);
    }

    public function testGetProductWithInvalidTokenShouldFail(): void
    {
        $user = $this->getUser();

        $response = $this->getJson(
            str_replace('{userId}', $user->getKey(), self::CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }

    public function testGetProductByAdminWithInvalidTokenShouldFail(): void
    {
        $user = $this->getAdminUser();

        $response = $this->getJson(
            str_replace('{userId}', $user->getKey(), self::ADMIN_CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }

    public function testGetAnotherUserCartShouldFail(): void
    {
        $user = $this->getUser();
        $anotherUser = $this->getAnotherUser();

        $response = $this->getJson(
            str_replace('{userId}', $anotherUser->getKey(), self::CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertForbidden();
    }
}
