<?php

namespace Tests\Feature\Controller\Auth;

use PHPUnit\Framework\Attributes\DataProvider;
use Tests\TestCase;

class LogoutTest extends TestCase
{
    private const USER_CONTROLLER_ROUTE = '/api/auth/logout';
    private const ADMIN_CONTROLLER_ROUTE = '/api/admin/auth/logout';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    #[DataProvider('contextDataProvider')]
    public function testLogoutShouldSuccess(string $route): void
    {
        $user = $this->getUser();
        $accessToken = $this->getUserAccessToken($user);
        $refreshToken = $this->getRefreshToken($user->id);
        $logoutResponse = $this->postJson(
            $route,
            [],
            [
                'authorization' => 'Bearer ' . $accessToken,
                'x-refresh-token' => $refreshToken,
            ]
        );
        $logoutResponse->assertOk();

        $ensureLogoutResponse = $this->postJson(
            $route,
            [],
            [
                'authorization' => 'Bearer ' . $accessToken,
                'x-refresh-token' => $refreshToken,
            ]
        );
        $ensureLogoutResponse->assertUnauthorized();
    }

    #[DataProvider('contextDataProvider')]
    public function testLogoutWithDeletedUserShouldFail(string $route): void
    {
        $user = $this->getUser();
        $accessToken = $this->getUserAccessToken($user);
        $refreshToken = $this->getRefreshToken($user->id);

        $user->delete();

        $logoutResponse = $this->postJson(
            $route,
            [],
            [
                'authorization' => 'Bearer ' . $accessToken,
                'x-refresh-token' => $refreshToken,
            ]
        );
        $logoutResponse->assertUnauthorized();
    }

    #[DataProvider('contextDataProvider')]
    public function testLogoutWithInvalidTokenShouldFail(string $route): void
    {
        $user = $this->getUser();
        $accessToken = $this->getInvalidToken();
        $refreshToken = $this->getRefreshToken($user->id);

        $logoutResponse = $this->postJson(
            $route,
            [],
            [
                'authorization' => 'Bearer ' . $accessToken,
                'x-refresh-token' => $refreshToken,
            ]
        );
        $logoutResponse->assertUnauthorized();
    }

    public static function contextDataProvider(): array
    {
        return [
            'user' => [
                'route' => self::USER_CONTROLLER_ROUTE,
            ],
            'admin' => [
                'route' => self::ADMIN_CONTROLLER_ROUTE,
            ]
        ];
    }
}
