<?php

namespace Tests\Feature\Controller\Product;

use PHPUnit\Framework\Attributes\DataProvider;
use Tests\TestCase;

class ProductGetTest extends TestCase
{
    private const USER_CONTROLLER_ROUTE = '/api/products/{id}';
    private const ADMIN_CONTROLLER_ROUTE = '/api/admin/products/{id}';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    #[DataProvider('contextDataProvider')]
    public function testGetProductShouldSuccess(\Closure $user, string $route): void
    {
        $expectedProduct = $this->createProduct();

        $response = $this->getJson(
            str_replace('{id}', $expectedProduct->id, $route),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user($this))]
        );

        $response->assertOk();
        $response->assertJson($expectedProduct->only([
            'title',
            'description',
            'type',
            'price',
        ]));
    }

    #[DataProvider('contextDataProvider')]
    public function testGetNonExistentProductShouldFail(\Closure $user, string $route): void
    {
        $response = $this->getJson(
            str_replace('{id}', rand(1000, 2000), $route),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user($this))]
        );

        $response->assertNotFound();
    }

    #[DataProvider('contextDataProvider')]
    public function testGetProductWithInvalidTokenShouldFail(\Closure $user, string $route): void
    {
        $expectedProduct = $this->createProduct();

        $response = $this->getJson(
            str_replace('{id}', $expectedProduct->id, $route),
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }

    public static function contextDataProvider(): array
    {
        return [
            'user' => [
                'user' => fn ($self) => $self->getUser(),
                'route' => self::USER_CONTROLLER_ROUTE,
            ],
            'admin' => [
                'user' => fn ($self) => $self->getAdminUser(),
                'route' => self::ADMIN_CONTROLLER_ROUTE,
            ]
        ];
    }
}
