<?php

namespace Tests\Feature\Controller\Product;

use PHPUnit\Framework\Attributes\DataProvider;
use Tests\TestCase;

class ProductIndexTest extends TestCase
{
    private const CONTROLLER_ROUTE = '/api/products';
    private const ADMIN_CONTROLLER_ROUTE = '/api/admin/products';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    #[DataProvider('contextDataProvider')]
    public function testGetProductsWithoutFiltersShouldSuccess(\Closure $user, string $route): void
    {
        $expectedResult['data'] = $this->getProducts();
        $expectedResult['pagination'] = [
            'currentPage' => 1,
            'perPage' => 15,
            'total' => count($expectedResult['data']),
        ];

        $response = $this->getJson(
            $route,
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user($this))]
        );

        $response->assertOk();
        $response->assertJson($expectedResult);
    }

    #[DataProvider('contextDataProvider')]
    public function testGetProductsWithFiltersShouldSuccess(\Closure $user, string $route): void
    {
        $filters = [
            'title' => 'testProduct',
            'description' => 'testDescription',
            'type' => 'pizza',
            'minPrice' => '30000000',
            'maxPrice' => '70000000',
        ];
        $productsForFilters = [
            [
                'title' => 'testProduct',
                'description' => 'testDescription',
                'type' => 'pizza',
                'price' => '40000000'
            ],
            [
                'title' => 'testProduct',
                'description' => 'testDescription',
                'type' => 'pizza',
                'price' => '50000000'
            ],
            [
                'title' => 'testProduct',
                'description' => 'testDescription',
                'type' => 'pizza',
                'price' => '60000000'
            ],
        ];
        $expectedResult['data'] = $this->createProducts($productsForFilters);
        $expectedResult['pagination'] = [
            'currentPage' => 1,
            'perPage' => 15,
            'total' => count($expectedResult['data']),
        ];

        $response = $this->getJson(
            $route . $this->addFilters($filters),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user($this))]
        );

        $response->assertOk();
        $response->assertJson($expectedResult);
    }

    #[DataProvider('contextDataProvider')]
    public function testGetProductsWithNotValidFiltersShouldFail(\Closure $user, string $route): void
    {
        $filters = $this->addFilters(['type' => 'fish']);
        $response = $this->getJson(
            $route . $filters,
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user($this))]
        );

        $response->assertUnprocessable();
    }

    #[DataProvider('contextDataProvider')]
    public function testGetProductsWithInvalidTokenShouldFail(\Closure $user, string $route): void
    {
        $response = $this->getJson(
            $route . '/' . rand(1000, 2000),
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }

    private function addFilters(array $filters): string
    {
        $filtersParams = '?';
        foreach ($filters as $filterName => $filterValue) {
            $filtersParams .= sprintf('%s=%s&', $filterName, $filterValue);
        }

        return $filtersParams;
    }

    public static function contextDataProvider(): array
    {
        return [
            'user' => [
                'user' => fn ($self) => $self->getUser(),
                'route' => self::CONTROLLER_ROUTE,
            ],
            'admin' => [
                'user' => fn ($self) => $self->getAdminUser(),
                'route' => self::ADMIN_CONTROLLER_ROUTE,
            ]
        ];
    }
}
