<?php

namespace Tests\Feature\Controller\Product;

use Tests\TestCase;

class ProductUpdateTest extends TestCase
{
    private const ADMIN_CONTROLLER_ROUTE = '/api/admin/products/{id}';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testProductUpdateShouldSuccess(): void
    {
        $adminUser = $this->getAdminUser();
        $product = $this->getRandomProduct();
        $productPropsToUpdate = [
            'title' => 'test title',
            'description' => 'test description',
            'type' => 'drink',
            'price' => 100,
        ];

        $response = $this->putJson(
            str_replace('{id}', $product->id, self::ADMIN_CONTROLLER_ROUTE),
            $productPropsToUpdate,
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($adminUser)]
        );
        $expectedProduct = $productPropsToUpdate;
        $expectedProduct['id'] = $product->id;

        $response->assertOk();
        $response->assertJson($expectedProduct);
    }

    public function testProductUpdateWithInvalidTokenShouldFail(): void
    {
        $product = $this->getRandomProduct();

        $response = $this->putJson(
            str_replace('{id}', $product->id, self::ADMIN_CONTROLLER_ROUTE),
            ['title' => 'Пицца века'],
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }

    public function testProductUpdateWithNonExistentProductShouldFail(): void
    {
        $adminUser = $this->getAdminUser();
        $response = $this->putJson(
            str_replace('{id}', rand(1000, 2000), self::ADMIN_CONTROLLER_ROUTE),
            ['title' => 'Пицца века'],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($adminUser)]
        );

        $response->assertNotFound();
    }

    public function testProductUpdateWithWithNotValidDataShouldFail(): void
    {
        $adminUser = $this->getAdminUser();
        $product = $this->getRandomProduct();

        $response = $this->putJson(
            str_replace('{id}', $product->id, self::ADMIN_CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($adminUser)]
        );

        $response->assertUnprocessable();
    }
}
