<?php

namespace Tests\Feature\Controller\Product;

use Tests\TestCase;

class ProductDeleteTest extends TestCase
{
    private const ADMIN_CONTROLLER_ROUTE = '/api/admin/products/{id}';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testDeleteProductShouldSuccess(): void
    {
        $adminUser = $this->getAdminUser();
        $product = $this->getRandomProduct();

        $response = $this->deleteJson(
            str_replace('{id}', $product->id, self::ADMIN_CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($adminUser)]
        );

        $response->assertOk();
        static::assertNull($this->getNullProduct($product->id));
    }

    public function testProductDeleteWithInvalidTokenShouldFail(): void
    {
        $product = $this->getRandomProduct();

        $response = $this->deleteJson(
            str_replace('{id}', $product->id, self::ADMIN_CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }

    public function testProductDeleteWithNonExistentProductShouldFail(): void
    {
        $adminUser = $this->getAdminUser();
        $response = $this->deleteJson(
            str_replace('{id}', rand(1000, 2000), self::ADMIN_CONTROLLER_ROUTE),
            [],
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($adminUser)]
        );

        $response->assertNotFound();
    }
}
