<?php

namespace Feature\Controller\Order;

use Tests\TestCase;

class OrderGetTest extends TestCase
{
    private const CONTROLLER_ROUTE = 'api/orders/{orderId}';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetOrderByOwnerSuccess(): void
    {
        $user = $this->getUser();
        $expectedResult = $this->createOrder($user);
        $response = $this->getJson(
            str_replace('{orderId}', $expectedResult['data']['id'], self::CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertOk();
        $response->assertJsonFragment($expectedResult['data']);
    }

    public function testGetOrderWithNonExistentOrderShouldFail(): void
    {
        $user = $this->getUser();
        $response = $this->getJson(
            str_replace('{orderId}', 99999, self::CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertNotFound();
    }

    public function testGetOrderByAnotherUserShouldFail(): void
    {
        $user = $this->getUser();
        $anotherUser = $this->getAnotherUser();
        $orderId = $this->getUserOrderId($anotherUser);
        $response = $this->getJson(
            str_replace('{orderId}', $orderId, self::CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertForbidden();
    }

    public function testGetOrderByOwnerWithInvalidTokenShouldFail(): void
    {
        $user = $this->getUser();
        $orderId = $this->getUserOrderId($user);
        $response = $this->getJson(
            str_replace('{orderId}', $orderId, self::CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }
}
