<?php

namespace Feature\Controller\Order;

use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class OrderIndexTest extends TestCase
{
    private const CONTROLLER_ROUTE = '/users/{userId}/orders';
    private const CONTROLLER_ADMIN_ROUTE = '/users/{userId}/orders';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetOrdersByOwnerSuccess(): void
    {
        $user = $this->getUser();
        $expectedOrders = $this->getOrders($user);
        $response = $this->getJson(
            str_replace('{userId}', $user->getKey(), self::CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertOk();
        $response->assertJson($expectedOrders);
    }
}
