<?php

namespace Feature\Controller\Order;

use Tests\TestCase;

class OrderGetTest extends TestCase
{
    private const CONTROLLER_ROUTE = 'api/orders/{orderId}';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetOrderByOwnerSuccess(): void
    {
        $user = $this->getUser();
        $expectedOrder = json_decode($this->getUserOrder($user), true);
        $orderId = $this->getUserOrderId($user);
        $response = $this->getJson(
            str_replace('{orderId}', $orderId, self::CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertOk();
        $response->assertJson($expectedOrder);
    }

    public function testGetOrderByAnotherUserShouldFail(): void
    {
        $user = $this->getUser();
        $anotherUser = $this->getAnotherUser();
        $orderId = $this->getUserOrderId($anotherUser);
        $response = $this->getJson(
            str_replace('{orderId}', $orderId, self::CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getUserAccessToken($user)]
        );

        $response->assertForbidden();
    }

    public function testGetOrderByOwnerWithInvalidCredentials(): void
    {
        $user = $this->getUser();
        $orderId = $this->getUserOrderId($user);
        $response = $this->getJson(
            str_replace('{orderId}', $orderId, self::CONTROLLER_ROUTE),
            ['authorization' => 'Bearer ' . $this->getInvalidToken()]
        );

        $response->assertUnauthorized();
    }

}
